/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.ui.contentassist;

import mx.infotec.dads.kukulkan.ui.contentassist.AbstractKukulkanProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class KukulkanProposalProvider extends AbstractKukulkanProposalProvider {
}
