/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKukulkanScopeProvider extends DelegatingScopeProvider {
}
