/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.ui;

import com.google.inject.Injector;
import mx.infotec.dads.kukulkan.ui.internal.KukulkanActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KukulkanExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(KukulkanActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		KukulkanActivator activator = KukulkanActivator.getInstance();
		return activator != null ? activator.getInjector(KukulkanActivator.MX_INFOTEC_DADS_KUKULKAN_KUKULKAN) : null;
	}

}
