/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractKukulkanValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage.eINSTANCE);
		return result;
	}
	
}
