/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan;

import mx.infotec.dads.kukulkan.KukulkanStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KukulkanStandaloneSetup extends KukulkanStandaloneSetupGenerated {
  public static void doSetup() {
    new KukulkanStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
