/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan;

import mx.infotec.dads.kukulkan.AbstractKukulkanRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KukulkanRuntimeModule extends AbstractKukulkanRuntimeModule {
}
