/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkangrammar.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class KukulkanUiModule extends AbstractKukulkanUiModule {
}
