/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkangrammar.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(KukulkanInjectorProvider)
class KukulkanParsingTest {
	
	@Test
	def void loadModel() {

	}
}
