/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkangrammar.ide


/**
 * Use this class to register ide components.
 */
class KukulkanIdeModule extends AbstractKukulkanIdeModule {
}
