/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KukulkanAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("mx/infotec/dads/kukulkan/parser/antlr/internal/InternalKukulkan.tokens");
	}
}
