/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.resource.IResourceFactory;
import org.eclipse.xtext.resource.IResourceServiceProvider;

@SuppressWarnings("all")
public class KukulkanStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new KukulkanRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.infotec.mx/dads/kukulkan/Kukulkan")) {
			EPackage.Registry.INSTANCE.put("http://www.infotec.mx/dads/kukulkan/Kukulkan", KukulkanPackage.eINSTANCE);
		}
		IResourceFactory resourceFactory = injector.getInstance(IResourceFactory.class);
		IResourceServiceProvider serviceProvider = injector.getInstance(IResourceServiceProvider.class);
		
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("3k", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("3k", serviceProvider);
		Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap().put("kukulkan", resourceFactory);
		IResourceServiceProvider.Registry.INSTANCE.getExtensionToFactoryMap().put("kukulkan", serviceProvider);
	}
}
