/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>association Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getType <em>Type</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getToSourcePropertyName <em>To Source Property Name</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getTargetEntity <em>Target Entity</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getassociationField()
 * @model
 * @generated
 */
public interface associationField extends entityField
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getassociationField_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>To Source Property Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>To Source Property Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>To Source Property Name</em>' attribute.
   * @see #setToSourcePropertyName(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getassociationField_ToSourcePropertyName()
   * @model
   * @generated
   */
  String getToSourcePropertyName();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getToSourcePropertyName <em>To Source Property Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>To Source Property Name</em>' attribute.
   * @see #getToSourcePropertyName()
   * @generated
   */
  void setToSourcePropertyName(String value);

  /**
   * Returns the value of the '<em><b>Target Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Target Entity</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Entity</em>' reference.
   * @see #setTargetEntity(entity)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getassociationField_TargetEntity()
   * @model
   * @generated
   */
  entity getTargetEntity();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getTargetEntity <em>Target Entity</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Entity</em>' reference.
   * @see #getTargetEntity()
   * @generated
   */
  void setTargetEntity(entity value);

} // associationField
