/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage
 * @generated
 */
public interface KukulkanFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KukulkanFactory eINSTANCE = mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanFactoryImpl.init();

  /**
   * Returns a new object of class '<em>domain Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>domain Model</em>'.
   * @generated
   */
  domainModel createdomainModel();

  /**
   * Returns a new object of class '<em>entity</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>entity</em>'.
   * @generated
   */
  entity createentity();

  /**
   * Returns a new object of class '<em>entity Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>entity Field</em>'.
   * @generated
   */
  entityField createentityField();

  /**
   * Returns a new object of class '<em>primitive Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>primitive Field</em>'.
   * @generated
   */
  primitiveField createprimitiveField();

  /**
   * Returns a new object of class '<em>field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>field Type</em>'.
   * @generated
   */
  fieldType createfieldType();

  /**
   * Returns a new object of class '<em>association Field</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>association Field</em>'.
   * @generated
   */
  associationField createassociationField();

  /**
   * Returns a new object of class '<em>string Field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string Field Type</em>'.
   * @generated
   */
  stringFieldType createstringFieldType();

  /**
   * Returns a new object of class '<em>numeric Field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>numeric Field Type</em>'.
   * @generated
   */
  numericFieldType createnumericFieldType();

  /**
   * Returns a new object of class '<em>boolean Field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>boolean Field Type</em>'.
   * @generated
   */
  booleanFieldType createbooleanFieldType();

  /**
   * Returns a new object of class '<em>date Field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>date Field Type</em>'.
   * @generated
   */
  dateFieldType createdateFieldType();

  /**
   * Returns a new object of class '<em>blob Field Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>blob Field Type</em>'.
   * @generated
   */
  blobFieldType createblobFieldType();

  /**
   * Returns a new object of class '<em>string Validators</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>string Validators</em>'.
   * @generated
   */
  stringValidators createstringValidators();

  /**
   * Returns a new object of class '<em>numeric Validators</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>numeric Validators</em>'.
   * @generated
   */
  numericValidators createnumericValidators();

  /**
   * Returns a new object of class '<em>blob Validators</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>blob Validators</em>'.
   * @generated
   */
  blobValidators createblobValidators();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  KukulkanPackage getKukulkanPackage();

} //KukulkanFactory
