/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanFactory
 * @model kind="package"
 * @generated
 */
public interface KukulkanPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "kukulkan";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.infotec.mx/dads/kukulkan/Kukulkan";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "kukulkan";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  KukulkanPackage eINSTANCE = mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl.init();

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.domainModelImpl <em>domain Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.domainModelImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getdomainModel()
   * @generated
   */
  int DOMAIN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Entities</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL__ENTITIES = 0;

  /**
   * The number of structural features of the '<em>domain Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAIN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.entityImpl <em>entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.entityImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getentity()
   * @generated
   */
  int ENTITY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = 0;

  /**
   * The feature id for the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__TABLE_NAME = 1;

  /**
   * The feature id for the '<em><b>Fields</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__FIELDS = 2;

  /**
   * The number of structural features of the '<em>entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.entityFieldImpl <em>entity Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.entityFieldImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getentityField()
   * @generated
   */
  int ENTITY_FIELD = 2;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD__ID = 0;

  /**
   * The number of structural features of the '<em>entity Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FIELD_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.primitiveFieldImpl <em>primitive Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.primitiveFieldImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getprimitiveField()
   * @generated
   */
  int PRIMITIVE_FIELD = 3;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_FIELD__ID = ENTITY_FIELD__ID;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_FIELD__TYPE = ENTITY_FIELD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>primitive Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRIMITIVE_FIELD_FEATURE_COUNT = ENTITY_FIELD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.fieldTypeImpl <em>field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.fieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getfieldType()
   * @generated
   */
  int FIELD_TYPE = 4;

  /**
   * The number of structural features of the '<em>field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.associationFieldImpl <em>association Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.associationFieldImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getassociationField()
   * @generated
   */
  int ASSOCIATION_FIELD = 5;

  /**
   * The feature id for the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FIELD__ID = ENTITY_FIELD__ID;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FIELD__TYPE = ENTITY_FIELD_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>To Source Property Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FIELD__TO_SOURCE_PROPERTY_NAME = ENTITY_FIELD_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FIELD__TARGET_ENTITY = ENTITY_FIELD_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>association Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSOCIATION_FIELD_FEATURE_COUNT = ENTITY_FIELD_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.stringFieldTypeImpl <em>string Field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.stringFieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getstringFieldType()
   * @generated
   */
  int STRING_FIELD_TYPE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FIELD_TYPE__NAME = FIELD_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FIELD_TYPE__CONSTRAINTS = FIELD_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>string Field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_FIELD_TYPE_FEATURE_COUNT = FIELD_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.numericFieldTypeImpl <em>numeric Field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.numericFieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getnumericFieldType()
   * @generated
   */
  int NUMERIC_FIELD_TYPE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_FIELD_TYPE__NAME = FIELD_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_FIELD_TYPE__CONSTRAINTS = FIELD_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>numeric Field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_FIELD_TYPE_FEATURE_COUNT = FIELD_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.booleanFieldTypeImpl <em>boolean Field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.booleanFieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getbooleanFieldType()
   * @generated
   */
  int BOOLEAN_FIELD_TYPE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FIELD_TYPE__NAME = FIELD_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FIELD_TYPE__REQUIRED = FIELD_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>boolean Field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_FIELD_TYPE_FEATURE_COUNT = FIELD_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.dateFieldTypeImpl <em>date Field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.dateFieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getdateFieldType()
   * @generated
   */
  int DATE_FIELD_TYPE = 9;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FIELD_TYPE__TYPE = FIELD_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FIELD_TYPE__REQUIRED = FIELD_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>date Field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATE_FIELD_TYPE_FEATURE_COUNT = FIELD_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.blobFieldTypeImpl <em>blob Field Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.blobFieldTypeImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getblobFieldType()
   * @generated
   */
  int BLOB_FIELD_TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_FIELD_TYPE__NAME = FIELD_TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_FIELD_TYPE__CONSTRAINTS = FIELD_TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>blob Field Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_FIELD_TYPE_FEATURE_COUNT = FIELD_TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.stringValidatorsImpl <em>string Validators</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.stringValidatorsImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getstringValidators()
   * @generated
   */
  int STRING_VALIDATORS = 11;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALIDATORS__REQUIRED = 0;

  /**
   * The feature id for the '<em><b>Min Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALIDATORS__MIN_LENGHT = 1;

  /**
   * The feature id for the '<em><b>Max Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALIDATORS__MAX_LENGHT = 2;

  /**
   * The feature id for the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALIDATORS__PATTERN = 3;

  /**
   * The number of structural features of the '<em>string Validators</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALIDATORS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.numericValidatorsImpl <em>numeric Validators</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.numericValidatorsImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getnumericValidators()
   * @generated
   */
  int NUMERIC_VALIDATORS = 12;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_VALIDATORS__REQUIRED = 0;

  /**
   * The feature id for the '<em><b>Min Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_VALIDATORS__MIN_VALUE = 1;

  /**
   * The feature id for the '<em><b>Max Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_VALIDATORS__MAX_VALUE = 2;

  /**
   * The number of structural features of the '<em>numeric Validators</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMERIC_VALIDATORS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.blobValidatorsImpl <em>blob Validators</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.blobValidatorsImpl
   * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getblobValidators()
   * @generated
   */
  int BLOB_VALIDATORS = 13;

  /**
   * The feature id for the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_VALIDATORS__REQUIRED = 0;

  /**
   * The feature id for the '<em><b>Min Bytes Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_VALIDATORS__MIN_BYTES_VALUE = 1;

  /**
   * The feature id for the '<em><b>Max Bytes Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_VALIDATORS__MAX_BYTES_VALUE = 2;

  /**
   * The number of structural features of the '<em>blob Validators</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOB_VALIDATORS_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.domainModel <em>domain Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>domain Model</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.domainModel
   * @generated
   */
  EClass getdomainModel();

  /**
   * Returns the meta object for the containment reference list '{@link mx.infotec.dads.kukulkan.kukulkan.domainModel#getEntities <em>Entities</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entities</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.domainModel#getEntities()
   * @see #getdomainModel()
   * @generated
   */
  EReference getdomainModel_Entities();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.entity <em>entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>entity</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entity
   * @generated
   */
  EClass getentity();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.entity#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entity#getName()
   * @see #getentity()
   * @generated
   */
  EAttribute getentity_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.entity#getTableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entity#getTableName()
   * @see #getentity()
   * @generated
   */
  EAttribute getentity_TableName();

  /**
   * Returns the meta object for the containment reference list '{@link mx.infotec.dads.kukulkan.kukulkan.entity#getFields <em>Fields</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Fields</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entity#getFields()
   * @see #getentity()
   * @generated
   */
  EReference getentity_Fields();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.entityField <em>entity Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>entity Field</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entityField
   * @generated
   */
  EClass getentityField();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.entityField#getId <em>Id</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Id</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.entityField#getId()
   * @see #getentityField()
   * @generated
   */
  EAttribute getentityField_Id();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.primitiveField <em>primitive Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>primitive Field</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.primitiveField
   * @generated
   */
  EClass getprimitiveField();

  /**
   * Returns the meta object for the containment reference '{@link mx.infotec.dads.kukulkan.kukulkan.primitiveField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.primitiveField#getType()
   * @see #getprimitiveField()
   * @generated
   */
  EReference getprimitiveField_Type();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.fieldType <em>field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.fieldType
   * @generated
   */
  EClass getfieldType();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.associationField <em>association Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>association Field</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.associationField
   * @generated
   */
  EClass getassociationField();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.associationField#getType()
   * @see #getassociationField()
   * @generated
   */
  EAttribute getassociationField_Type();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getToSourcePropertyName <em>To Source Property Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>To Source Property Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.associationField#getToSourcePropertyName()
   * @see #getassociationField()
   * @generated
   */
  EAttribute getassociationField_ToSourcePropertyName();

  /**
   * Returns the meta object for the reference '{@link mx.infotec.dads.kukulkan.kukulkan.associationField#getTargetEntity <em>Target Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Entity</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.associationField#getTargetEntity()
   * @see #getassociationField()
   * @generated
   */
  EReference getassociationField_TargetEntity();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.stringFieldType <em>string Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>string Field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringFieldType
   * @generated
   */
  EClass getstringFieldType();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.stringFieldType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringFieldType#getName()
   * @see #getstringFieldType()
   * @generated
   */
  EAttribute getstringFieldType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mx.infotec.dads.kukulkan.kukulkan.stringFieldType#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringFieldType#getConstraints()
   * @see #getstringFieldType()
   * @generated
   */
  EReference getstringFieldType_Constraints();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType <em>numeric Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>numeric Field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericFieldType
   * @generated
   */
  EClass getnumericFieldType();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getName()
   * @see #getnumericFieldType()
   * @generated
   */
  EAttribute getnumericFieldType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getConstraints()
   * @see #getnumericFieldType()
   * @generated
   */
  EReference getnumericFieldType_Constraints();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType <em>boolean Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>boolean Field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.booleanFieldType
   * @generated
   */
  EClass getbooleanFieldType();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getName()
   * @see #getbooleanFieldType()
   * @generated
   */
  EAttribute getbooleanFieldType_Name();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getRequired()
   * @see #getbooleanFieldType()
   * @generated
   */
  EAttribute getbooleanFieldType_Required();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType <em>date Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>date Field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.dateFieldType
   * @generated
   */
  EClass getdateFieldType();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getType()
   * @see #getdateFieldType()
   * @generated
   */
  EAttribute getdateFieldType_Type();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getRequired()
   * @see #getdateFieldType()
   * @generated
   */
  EAttribute getdateFieldType_Required();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.blobFieldType <em>blob Field Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>blob Field Type</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobFieldType
   * @generated
   */
  EClass getblobFieldType();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.blobFieldType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobFieldType#getName()
   * @see #getblobFieldType()
   * @generated
   */
  EAttribute getblobFieldType_Name();

  /**
   * Returns the meta object for the containment reference list '{@link mx.infotec.dads.kukulkan.kukulkan.blobFieldType#getConstraints <em>Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Constraints</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobFieldType#getConstraints()
   * @see #getblobFieldType()
   * @generated
   */
  EReference getblobFieldType_Constraints();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators <em>string Validators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>string Validators</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringValidators
   * @generated
   */
  EClass getstringValidators();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringValidators#getRequired()
   * @see #getstringValidators()
   * @generated
   */
  EAttribute getstringValidators_Required();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMinLenght <em>Min Lenght</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Lenght</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMinLenght()
   * @see #getstringValidators()
   * @generated
   */
  EAttribute getstringValidators_MinLenght();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMaxLenght <em>Max Lenght</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Lenght</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMaxLenght()
   * @see #getstringValidators()
   * @generated
   */
  EAttribute getstringValidators_MaxLenght();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getPattern <em>Pattern</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pattern</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.stringValidators#getPattern()
   * @see #getstringValidators()
   * @generated
   */
  EAttribute getstringValidators_Pattern();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.numericValidators <em>numeric Validators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>numeric Validators</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericValidators
   * @generated
   */
  EClass getnumericValidators();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.numericValidators#getRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericValidators#getRequired()
   * @see #getnumericValidators()
   * @generated
   */
  EAttribute getnumericValidators_Required();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.numericValidators#getMinValue <em>Min Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Value</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericValidators#getMinValue()
   * @see #getnumericValidators()
   * @generated
   */
  EAttribute getnumericValidators_MinValue();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.numericValidators#getMaxValue <em>Max Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Value</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.numericValidators#getMaxValue()
   * @see #getnumericValidators()
   * @generated
   */
  EAttribute getnumericValidators_MaxValue();

  /**
   * Returns the meta object for class '{@link mx.infotec.dads.kukulkan.kukulkan.blobValidators <em>blob Validators</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>blob Validators</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobValidators
   * @generated
   */
  EClass getblobValidators();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.blobValidators#getRequired <em>Required</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Required</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobValidators#getRequired()
   * @see #getblobValidators()
   * @generated
   */
  EAttribute getblobValidators_Required();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.blobValidators#getMinBytesValue <em>Min Bytes Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Min Bytes Value</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobValidators#getMinBytesValue()
   * @see #getblobValidators()
   * @generated
   */
  EAttribute getblobValidators_MinBytesValue();

  /**
   * Returns the meta object for the attribute '{@link mx.infotec.dads.kukulkan.kukulkan.blobValidators#getMaxBytesValue <em>Max Bytes Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Max Bytes Value</em>'.
   * @see mx.infotec.dads.kukulkan.kukulkan.blobValidators#getMaxBytesValue()
   * @see #getblobValidators()
   * @generated
   */
  EAttribute getblobValidators_MaxBytesValue();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  KukulkanFactory getKukulkanFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.domainModelImpl <em>domain Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.domainModelImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getdomainModel()
     * @generated
     */
    EClass DOMAIN_MODEL = eINSTANCE.getdomainModel();

    /**
     * The meta object literal for the '<em><b>Entities</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAIN_MODEL__ENTITIES = eINSTANCE.getdomainModel_Entities();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.entityImpl <em>entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.entityImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getentity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getentity();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__NAME = eINSTANCE.getentity_Name();

    /**
     * The meta object literal for the '<em><b>Table Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY__TABLE_NAME = eINSTANCE.getentity_TableName();

    /**
     * The meta object literal for the '<em><b>Fields</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__FIELDS = eINSTANCE.getentity_Fields();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.entityFieldImpl <em>entity Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.entityFieldImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getentityField()
     * @generated
     */
    EClass ENTITY_FIELD = eINSTANCE.getentityField();

    /**
     * The meta object literal for the '<em><b>Id</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_FIELD__ID = eINSTANCE.getentityField_Id();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.primitiveFieldImpl <em>primitive Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.primitiveFieldImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getprimitiveField()
     * @generated
     */
    EClass PRIMITIVE_FIELD = eINSTANCE.getprimitiveField();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRIMITIVE_FIELD__TYPE = eINSTANCE.getprimitiveField_Type();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.fieldTypeImpl <em>field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.fieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getfieldType()
     * @generated
     */
    EClass FIELD_TYPE = eINSTANCE.getfieldType();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.associationFieldImpl <em>association Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.associationFieldImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getassociationField()
     * @generated
     */
    EClass ASSOCIATION_FIELD = eINSTANCE.getassociationField();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_FIELD__TYPE = eINSTANCE.getassociationField_Type();

    /**
     * The meta object literal for the '<em><b>To Source Property Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSOCIATION_FIELD__TO_SOURCE_PROPERTY_NAME = eINSTANCE.getassociationField_ToSourcePropertyName();

    /**
     * The meta object literal for the '<em><b>Target Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSOCIATION_FIELD__TARGET_ENTITY = eINSTANCE.getassociationField_TargetEntity();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.stringFieldTypeImpl <em>string Field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.stringFieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getstringFieldType()
     * @generated
     */
    EClass STRING_FIELD_TYPE = eINSTANCE.getstringFieldType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_FIELD_TYPE__NAME = eINSTANCE.getstringFieldType_Name();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRING_FIELD_TYPE__CONSTRAINTS = eINSTANCE.getstringFieldType_Constraints();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.numericFieldTypeImpl <em>numeric Field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.numericFieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getnumericFieldType()
     * @generated
     */
    EClass NUMERIC_FIELD_TYPE = eINSTANCE.getnumericFieldType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMERIC_FIELD_TYPE__NAME = eINSTANCE.getnumericFieldType_Name();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMERIC_FIELD_TYPE__CONSTRAINTS = eINSTANCE.getnumericFieldType_Constraints();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.booleanFieldTypeImpl <em>boolean Field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.booleanFieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getbooleanFieldType()
     * @generated
     */
    EClass BOOLEAN_FIELD_TYPE = eINSTANCE.getbooleanFieldType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_FIELD_TYPE__NAME = eINSTANCE.getbooleanFieldType_Name();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_FIELD_TYPE__REQUIRED = eINSTANCE.getbooleanFieldType_Required();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.dateFieldTypeImpl <em>date Field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.dateFieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getdateFieldType()
     * @generated
     */
    EClass DATE_FIELD_TYPE = eINSTANCE.getdateFieldType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_FIELD_TYPE__TYPE = eINSTANCE.getdateFieldType_Type();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DATE_FIELD_TYPE__REQUIRED = eINSTANCE.getdateFieldType_Required();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.blobFieldTypeImpl <em>blob Field Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.blobFieldTypeImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getblobFieldType()
     * @generated
     */
    EClass BLOB_FIELD_TYPE = eINSTANCE.getblobFieldType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOB_FIELD_TYPE__NAME = eINSTANCE.getblobFieldType_Name();

    /**
     * The meta object literal for the '<em><b>Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BLOB_FIELD_TYPE__CONSTRAINTS = eINSTANCE.getblobFieldType_Constraints();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.stringValidatorsImpl <em>string Validators</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.stringValidatorsImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getstringValidators()
     * @generated
     */
    EClass STRING_VALIDATORS = eINSTANCE.getstringValidators();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALIDATORS__REQUIRED = eINSTANCE.getstringValidators_Required();

    /**
     * The meta object literal for the '<em><b>Min Lenght</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALIDATORS__MIN_LENGHT = eINSTANCE.getstringValidators_MinLenght();

    /**
     * The meta object literal for the '<em><b>Max Lenght</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALIDATORS__MAX_LENGHT = eINSTANCE.getstringValidators_MaxLenght();

    /**
     * The meta object literal for the '<em><b>Pattern</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALIDATORS__PATTERN = eINSTANCE.getstringValidators_Pattern();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.numericValidatorsImpl <em>numeric Validators</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.numericValidatorsImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getnumericValidators()
     * @generated
     */
    EClass NUMERIC_VALIDATORS = eINSTANCE.getnumericValidators();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMERIC_VALIDATORS__REQUIRED = eINSTANCE.getnumericValidators_Required();

    /**
     * The meta object literal for the '<em><b>Min Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMERIC_VALIDATORS__MIN_VALUE = eINSTANCE.getnumericValidators_MinValue();

    /**
     * The meta object literal for the '<em><b>Max Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMERIC_VALIDATORS__MAX_VALUE = eINSTANCE.getnumericValidators_MaxValue();

    /**
     * The meta object literal for the '{@link mx.infotec.dads.kukulkan.kukulkan.impl.blobValidatorsImpl <em>blob Validators</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.blobValidatorsImpl
     * @see mx.infotec.dads.kukulkan.kukulkan.impl.KukulkanPackageImpl#getblobValidators()
     * @generated
     */
    EClass BLOB_VALIDATORS = eINSTANCE.getblobValidators();

    /**
     * The meta object literal for the '<em><b>Required</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOB_VALIDATORS__REQUIRED = eINSTANCE.getblobValidators_Required();

    /**
     * The meta object literal for the '<em><b>Min Bytes Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOB_VALIDATORS__MIN_BYTES_VALUE = eINSTANCE.getblobValidators_MinBytesValue();

    /**
     * The meta object literal for the '<em><b>Max Bytes Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BLOB_VALIDATORS__MAX_BYTES_VALUE = eINSTANCE.getblobValidators_MaxBytesValue();

  }

} //KukulkanPackage
