/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>numeric Field Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getName <em>Name</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getConstraints <em>Constraints</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getnumericFieldType()
 * @model
 * @generated
 */
public interface numericFieldType extends fieldType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getnumericFieldType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.numericFieldType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Constraints</b></em>' containment reference list.
   * The list contents are of type {@link mx.infotec.dads.kukulkan.kukulkan.numericValidators}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constraints</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constraints</em>' containment reference list.
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getnumericFieldType_Constraints()
   * @model containment="true"
   * @generated
   */
  EList<numericValidators> getConstraints();

} // numericFieldType
