/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>string Validators</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getRequired <em>Required</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMinLenght <em>Min Lenght</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMaxLenght <em>Max Lenght</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getPattern <em>Pattern</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getstringValidators()
 * @model
 * @generated
 */
public interface stringValidators extends EObject
{
  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getstringValidators_Required()
   * @model
   * @generated
   */
  String getRequired();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #getRequired()
   * @generated
   */
  void setRequired(String value);

  /**
   * Returns the value of the '<em><b>Min Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Min Lenght</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Lenght</em>' attribute.
   * @see #setMinLenght(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getstringValidators_MinLenght()
   * @model
   * @generated
   */
  String getMinLenght();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMinLenght <em>Min Lenght</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Lenght</em>' attribute.
   * @see #getMinLenght()
   * @generated
   */
  void setMinLenght(String value);

  /**
   * Returns the value of the '<em><b>Max Lenght</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Max Lenght</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Lenght</em>' attribute.
   * @see #setMaxLenght(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getstringValidators_MaxLenght()
   * @model
   * @generated
   */
  String getMaxLenght();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getMaxLenght <em>Max Lenght</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Lenght</em>' attribute.
   * @see #getMaxLenght()
   * @generated
   */
  void setMaxLenght(String value);

  /**
   * Returns the value of the '<em><b>Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pattern</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern</em>' attribute.
   * @see #setPattern(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getstringValidators_Pattern()
   * @model
   * @generated
   */
  String getPattern();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.stringValidators#getPattern <em>Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern</em>' attribute.
   * @see #getPattern()
   * @generated
   */
  void setPattern(String value);

} // stringValidators
