/*
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.ui.tests;

import com.google.inject.Injector;
import mx.infotec.dads.kukulkan.ui.internal.KukulkanActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class KukulkanUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return KukulkanActivator.getInstance().getInjector("mx.infotec.dads.kukulkan.Kukulkan");
	}

}
