/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import mx.infotec.dads.kukulkan.KukulkanRuntimeModule;
import mx.infotec.dads.kukulkan.KukulkanStandaloneSetup;
import mx.infotec.dads.kukulkan.ide.KukulkanIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class KukulkanIdeSetup extends KukulkanStandaloneSetup {
  @Override
  public Injector createInjector() {
    KukulkanRuntimeModule _kukulkanRuntimeModule = new KukulkanRuntimeModule();
    KukulkanIdeModule _kukulkanIdeModule = new KukulkanIdeModule();
    return Guice.createInjector(Modules2.mixin(_kukulkanRuntimeModule, _kukulkanIdeModule));
  }
}
