/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.ide;

import mx.infotec.dads.kukulkan.ide.AbstractKukulkanIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class KukulkanIdeModule extends AbstractKukulkanIdeModule {
}
