/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.validation;

import mx.infotec.dads.kukulkan.validation.AbstractKukulkanValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KukulkanValidator extends AbstractKukulkanValidator {
}
