/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>boolean Field Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getName <em>Name</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getRequired <em>Required</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getbooleanFieldType()
 * @model
 * @generated
 */
public interface booleanFieldType extends fieldType
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getbooleanFieldType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getbooleanFieldType_Required()
   * @model
   * @generated
   */
  String getRequired();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.booleanFieldType#getRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #getRequired()
   * @generated
   */
  void setRequired(String value);

} // booleanFieldType
