/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>date Field Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getType <em>Type</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getRequired <em>Required</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdateFieldType()
 * @model
 * @generated
 */
public interface dateFieldType extends fieldType
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdateFieldType_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Required</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Required</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Required</em>' attribute.
   * @see #setRequired(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdateFieldType_Required()
   * @model
   * @generated
   */
  String getRequired();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.dateFieldType#getRequired <em>Required</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Required</em>' attribute.
   * @see #getRequired()
   * @generated
   */
  void setRequired(String value);

} // dateFieldType
