/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>domain Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.domainModel#getEntities <em>Entities</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.domainModel#getSettings <em>Settings</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdomainModel()
 * @model
 * @generated
 */
public interface domainModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Entities</b></em>' containment reference list.
   * The list contents are of type {@link mx.infotec.dads.kukulkan.kukulkan.entity}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Entities</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entities</em>' containment reference list.
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdomainModel_Entities()
   * @model containment="true"
   * @generated
   */
  EList<entity> getEntities();

  /**
   * Returns the value of the '<em><b>Settings</b></em>' containment reference list.
   * The list contents are of type {@link mx.infotec.dads.kukulkan.kukulkan.option}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Settings</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Settings</em>' containment reference list.
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getdomainModel_Settings()
   * @model containment="true"
   * @generated
   */
  EList<option> getSettings();

} // domainModel
