/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>entity Field</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.entityField#getId <em>Id</em>}</li>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.entityField#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getentityField()
 * @model
 * @generated
 */
public interface entityField extends EObject
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Id</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getentityField_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.entityField#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(fieldType)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getentityField_Type()
   * @model containment="true"
   * @generated
   */
  fieldType getType();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.entityField#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(fieldType value);

} // entityField
