/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>entity Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getentityType()
 * @model
 * @generated
 */
public interface entityType extends fieldType
{
} // entityType
