/**
 * generated by Xtext 2.13.0
 */
package mx.infotec.dads.kukulkan.kukulkan;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>option</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mx.infotec.dads.kukulkan.kukulkan.option#getSetting <em>Setting</em>}</li>
 * </ul>
 *
 * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getoption()
 * @model
 * @generated
 */
public interface option extends EObject
{
  /**
   * Returns the value of the '<em><b>Setting</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Setting</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Setting</em>' attribute.
   * @see #setSetting(String)
   * @see mx.infotec.dads.kukulkan.kukulkan.KukulkanPackage#getoption_Setting()
   * @model
   * @generated
   */
  String getSetting();

  /**
   * Sets the value of the '{@link mx.infotec.dads.kukulkan.kukulkan.option#getSetting <em>Setting</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Setting</em>' attribute.
   * @see #getSetting()
   * @generated
   */
  void setSetting(String value);

} // option
